### ISSUE TITLE
Graph shows displaced on resolutions other than 1920x1080

### ISSUE THREAD

**Issue by Cobo3** [adamgerhant/Rank-Grapher#1]
When running the game at resolutions other than 1920x1080, the graph is not placed under the scoreboard.

The screenshot is taken at a resolution of 2560x1440. You can see the graph is placed on top of the scoreboard, which hides the stats.
This happens more or less the same in other resolutions (bother higher and lower than 1920x1080).
![imagen](https://user-images.githubusercontent.com/3205873/218711093-a5bc2c1f-8e5b-49d1-8bc1-c2ec03079e15.png)

**Comment by adamgerhant** [comment]
It seems that it is being positioned at the same pixel position regardless
of resolution. I think I could fix it, an update should be made in a few
days.

Thanks for the feedback

**Comment by Cobo3** [comment]
@adamgerhant Hey, sorry to bother. Could you please make an update on the bakkesplugins website please?

**Comment by adamgerhant** [comment]
I’ve tried making a request to update but it hasn’t gone through. The DLL
is in the github repo
