### ISSUE TITLE
why not just publish the latest dll on the repo's releases section or on bakkesmod site?

### ISSUE THREAD

**Issue by somombo** [adamgerhant/Rank-Grapher#2]
> For latest version with support for 2540x1440 resolution, download updated dll from github and replace the existing dll in bakkesmod/plugins.

there was a not on the bakkesmod page to get the latest dll from github.. why not just publish that on bakkesmod properly or on repos releases section?

**Comment by adamgerhant** [comment]
I tried updating the files but it didn’t work. System is pretty buggy and
there’s no good support. I can put the DLL in a release though

**Comment by somombo** [comment]
hmm fair enough.. thanks
